name: Performance Test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      run_db_bench_small_obj:
        type: boolean
        description: run_db_bench_small_obj
      run_db_bench_large_obj:
        type: boolean
        description: run_db_bench_large_obj
      run_db_bench_huge_memtable:
        type: boolean
        description: run_db_bench_huge_memtable
  

jobs:
  perf_test:    
    runs-on: perftest
    
    steps:

      - name: Run autoperf script via remotnic
        run: |
          echo Run auto perf test
          echo ${{ github.event.inputs.run_db_bench_small_obj }}
          echo ${{ github.event.inputs.run_db_bench_large_obj }}
          echo ${{ github.event.inputs.run_db_bench_huge_memtable }}
          #echo  ${{ github.sender.login }} 
          #ssh -i ~/remo.k remo@9.148.1.183 /home/remo/tremotnic.sh main HG_auto_T1 ${{ github.event.pusher.name }} 
          if ${{ github.event.inputs.run_db_bench_small_obj }} == true; then
            echo run_db_bench_small_obj
          fi
          #ssh -i ~/remo.k remo@9.148.1.183 /home/remo/tremotnic.sh main HG_auto_T1 ${{ github.actor }} run_db_bench_large_obj
          #ssh -i ~/remo.k remo@9.148.1.183 /home/remo/tremotnic.sh main HG_auto_T1 ${{ github.event.pusher.name }} run_db_bench_small_obj
          #ssh -i ~/remo.k remo@9.148.1.183 /home/remo/tremotnic.sh main HG_auto_T1 ${{ github.event.pusher.name }} run_db_bench_huge_memtable


